version: '{build}'
image: Visual Studio 2017
platform:
- x64

environment:
  matrix:
  - CONDA: 36-x64
  #- CONDA: 37-x64

init:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- ps: $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"

install:
- ps: |
    git submodule update -q --init --recursive
    powershell .\install.ps1

build_script:
- ps: |
    powershell .\build.ps1

artifacts:
  - path: 'conda-bld\win-*\*.tar.bz2'
